# Generated by Django 5.2.10 on 2026-02-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=15, verbose_name='課程名稱')),
                ('teacher', models.CharField(max_length=5, verbose_name='課程名稱')),
                ('course_date', models.DateField(verbose_name='授課日期')),
            ],
        ),
        migrations.CreateModel(
            name='update_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=15, verbose_name='上傳區域名稱')),
                ('introduce', models.TextField(verbose_name='說明')),
                ('amount', models.IntegerField(default=0, verbose_name='檔案數')),
            ],
        ),
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='學習歷程檔案名稱')),
                ('desc', models.TextField(verbose_name='說明')),
                ('jpg', models.FileField(upload_to='jpg/')),
                ('classes_id', models.IntegerField(verbose_name='課程編號編號')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='建立日期')),
                ('Certification', models.BooleanField(default=False, verbose_name='是否需要認證')),
                ('topic_id', models.IntegerField(verbose_name='上傳區域編號')),
            ],
        ),
    ]
