# Generated by Django 5.2.10 on 2026-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.CharField(max_length=5, verbose_name='授課老師'),
        ),
    ]
