# Generated by Django 5.2.10 on 2026-02-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='classes_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='課程編號編號'),
        ),
    ]
