# Generated by Django 5.2.10 on 2026-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_works_classes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='audit_status',
            field=models.CharField(choices=[('pending', '待處理'), ('approved', '同意'), ('rejected', '不同意')], default='pending', max_length=10, verbose_name='審核狀態'),
        ),
        migrations.AddField(
            model_name='works',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True, verbose_name='老師評論'),
        ),
    ]
