# Generated by Django 5.2.10 on 2026-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_alter_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='course_date',
            field=models.DateTimeField(verbose_name='授課日期'),
        ),
    ]
