# Generated by Django 5.2.10 on 2026-02-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_alter_classes_course_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='course_date',
        ),
        migrations.AddField(
            model_name='classes',
            name='course_enddate',
            field=models.DateField(blank=True, null=True, verbose_name='授課結束日期'),
        ),
        migrations.AddField(
            model_name='classes',
            name='course_startdate',
            field=models.DateField(blank=True, null=True, verbose_name='授課開始日期'),
        ),
    ]
