# Generated by Django 5.2.10 on 2026-02-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_remove_classes_course_date_classes_course_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=15, verbose_name='上傳區域名稱')),
                ('introduce', models.TextField(verbose_name='說明')),
                ('amount', models.IntegerField(default=0, verbose_name='檔案數')),
            ],
        ),
        migrations.DeleteModel(
            name='update_option',
        ),
        migrations.AlterField(
            model_name='works',
            name='jpg',
            field=models.FileField(blank=True, null=True, upload_to='jpg/'),
        ),
    ]
